const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const STORAGE_KEY = 'love-50-01-data';
const MAX_IMAGE_SIZE = 2 * 1024 * 1024;
const MAX_AUDIO_SIZE = 5 * 1024 * 1024;
const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const form = $('#love-form');
const screens = { form: $('#form-screen'), welcome: $('#welcome-screen'), love: $('#love-screen') };
const inputs = { senderName: $('#sender-name'), receiverName: $('#receiver-name'), message: $('#message'), letter: $('#letter'), specialDate: $('#special-date'), senderPhoto: $('#sender-photo'), receiverPhoto: $('#receiver-photo'), albumPhotos: $('#album-photos'), musicFile: $('#music-file'), qrContent: $('#qr-content') };
const imageDefaults = { senderPhoto: createAvatar('#f7c8cc', '#c95d70'), receiverPhoto: createAvatar('#ead9ee', '#9d668b') };
let data = { senderName: '', receiverName: '', message: '', letter: '', specialDate: '', senderPhoto: '', receiverPhoto: '', album: [], musicMode: 'none', musicName: '', musicData: '', qrEnabled: false, qrContent: '' };
let imageUrls = { ...imageDefaults };
let selectedAlbum = [];
let currentLightboxIndex = 0;
let counterTimer;
let particleTimer;

function createAvatar(background, foreground) { const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><rect width="200" height="200" fill="${background}"/><circle cx="100" cy="77" r="36" fill="${foreground}" opacity=".55"/><path d="M31 190c8-46 34-68 69-68s61 22 69 68" fill="${foreground}" opacity=".55"/><text x="100" y="177" fill="white" font-size="28" text-anchor="middle">♥</text></svg>`; return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`; }
function readFile(file, maxSize, typeLabel) { return new Promise((resolve, reject) => { if (!file) return resolve(''); if (file.size > maxSize) return reject(new Error(`${typeLabel} quá lớn. Vui lòng chọn file nhỏ hơn ${Math.round(maxSize / 1024 / 1024)}MB.`)); const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => reject(new Error(`Không thể đọc ${typeLabel.toLowerCase()}.`)); reader.readAsDataURL(file); }); }
function showStatus(message = '') { $('#form-status').textContent = message; }
function setError(field, message) { const error = $(`#${field}-error`); const element = inputs[field]; if (error) error.textContent = message; if (element) element.setAttribute('aria-invalid', message ? 'true' : 'false'); }
function syncCounter(input, counter) { counter.textContent = `${input.value.length} / ${input.maxLength}`; }
function formatDate(value) { if (!value) return 'Một ngày thật đặc biệt của chúng mình'; return new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date(`${value}T00:00:00`)); }
function updateImagePreview(inputName, url) { const preview = $(`#${inputName.replace('Photo', '')}-preview`); if (url) preview.innerHTML = `<img src="${url}" alt="Ảnh đã chọn">`; }
function renderAlbumPreview() { const container = $('#album-preview'); container.innerHTML = selectedAlbum.map((url, index) => `<img src="${url}" alt="Ảnh album ${index + 1}">`).join(''); container.hidden = selectedAlbum.length === 0; $('#album-status').textContent = selectedAlbum.length ? `Đã chọn ${selectedAlbum.length}/6 ảnh` : 'Thêm những khoảnh khắc đáng nhớ'; }
async function handleSingleImage(fieldName) { const file = inputs[fieldName].files[0]; if (!file) return; try { const url = await readFile(file, MAX_IMAGE_SIZE, 'Ảnh'); imageUrls[fieldName] = url; updateImagePreview(fieldName, url); showStatus(''); } catch (error) { inputs[fieldName].value = ''; showStatus(error.message); } }
async function handleAlbum() { const files = [...inputs.albumPhotos.files].slice(0, 6); if (inputs.albumPhotos.files.length > 6) showStatus('Album chỉ nhận tối đa 6 ảnh. Sáu ảnh đầu tiên đã được chọn.'); const urls = []; for (const file of files) { try { urls.push(await readFile(file, MAX_IMAGE_SIZE, 'Ảnh album')); } catch (error) { showStatus(error.message); } } selectedAlbum = urls; renderAlbumPreview(); }
async function handleMusic() { const file = inputs.musicFile.files[0]; if (!file) return; try { data.musicData = await readFile(file, MAX_AUDIO_SIZE, 'File nhạc'); data.musicName = file.name; $('#music-name').textContent = file.name; const preview = $('#music-preview'); preview.src = data.musicData; preview.hidden = false; showStatus(''); } catch (error) { inputs.musicFile.value = ''; showStatus(error.message); } }
function saveData() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...data, senderPhoto: imageUrls.senderPhoto, receiverPhoto: imageUrls.receiverPhoto, album: selectedAlbum })); return true; } catch { showStatus('Dữ liệu hơi lớn để lưu trên thiết bị. Trang vẫn hoạt động, nhưng ảnh có thể không được khôi phục sau khi tải lại.'); return false; } }
function readForm() { data.senderName = inputs.senderName.value.trim(); data.receiverName = inputs.receiverName.value.trim(); data.message = inputs.message.value.trim(); data.letter = inputs.letter.value.trim(); data.specialDate = inputs.specialDate.value; data.musicMode = $('input[name="musicMode"]:checked').value; data.qrEnabled = $('#qr-enabled').checked; data.qrContent = inputs.qrContent.value.trim(); data.senderPhoto = imageUrls.senderPhoto; data.receiverPhoto = imageUrls.receiverPhoto; data.album = selectedAlbum; }
function populateForm(saved) { data = { ...data, ...saved }; inputs.senderName.value = data.senderName; inputs.receiverName.value = data.receiverName; inputs.message.value = data.message; inputs.letter.value = data.letter; inputs.specialDate.value = data.specialDate; inputs.qrContent.value = data.qrContent; $('#qr-enabled').checked = Boolean(data.qrEnabled); $('input[name="musicMode"][value="' + (data.musicMode === 'music' ? 'music' : 'none') + '"]').checked = true; imageUrls.senderPhoto = data.senderPhoto || imageDefaults.senderPhoto; imageUrls.receiverPhoto = data.receiverPhoto || imageDefaults.receiverPhoto; selectedAlbum = Array.isArray(data.album) ? data.album : []; updateImagePreview('senderPhoto', imageUrls.senderPhoto); updateImagePreview('receiverPhoto', imageUrls.receiverPhoto); renderAlbumPreview(); syncOptionalSections(); syncCounter(inputs.message, $('#character-count')); syncCounter(inputs.letter, $('#letter-count')); if (data.musicName) { $('#music-name').textContent = data.musicName; $('#music-preview').src = data.musicData; $('#music-preview').hidden = !data.musicData; } }
function syncOptionalSections() { $('#music-upload').hidden = $('input[name="musicMode"]:checked').value !== 'music'; $('#qr-fields').hidden = !$('#qr-enabled').checked; }
function validate() { let valid = true; const sender = inputs.senderName.value.trim(); const receiver = inputs.receiverName.value.trim(); setError('senderName', sender ? '' : 'Vui lòng nhập tên người thứ nhất.'); setError('receiverName', receiver ? '' : 'Vui lòng nhập tên người thứ hai.'); if (!sender || !receiver) { (sender ? inputs.receiverName : inputs.senderName).focus(); valid = false; } return valid; }
function showScreen(screen) { Object.values(screens).forEach((item) => { item.hidden = item !== screen; }); window.scrollTo({ top: 0, behavior: prefersReducedMotion ? 'auto' : 'smooth' }); }
function renderResult() { $('#welcome-name').textContent = data.receiverName; $('#result-sender-name').textContent = data.senderName; $('#result-receiver-name').textContent = data.receiverName; $('#result-message').textContent = data.message || 'Mỗi khoảnh khắc bên nhau đều là một điều đáng nhớ.'; $('#result-date').textContent = `✦ ${formatDate(data.specialDate)} ✦`; $('#result-sender-photo').src = imageUrls.senderPhoto; $('#result-receiver-photo').src = imageUrls.receiverPhoto; renderCounter(); renderResultAlbum(); renderLetter(); renderQR(); renderMusic(); showScreen(screens.welcome); }
function renderCounter() { clearInterval(counterTimer); const note = $('#future-note'); if (!data.specialDate) { $('#counter-days').textContent = '∞'; $('#counter-hours').textContent = '—'; $('#counter-minutes').textContent = '—'; $('#counter-seconds').textContent = '—'; note.hidden = false; note.textContent = 'Ngày đặc biệt của hai bạn sẽ làm khoảnh khắc này thêm ý nghĩa.'; return; } const update = () => { const start = new Date(`${data.specialDate}T00:00:00`); const difference = Date.now() - start.getTime(); if (difference < 0) { $('#counter-days').textContent = '0'; $('#counter-hours').textContent = '0'; $('#counter-minutes').textContent = '0'; $('#counter-seconds').textContent = '0'; note.hidden = false; note.textContent = 'Ngày đặc biệt ấy vẫn đang ở phía trước 💗'; return; } const seconds = Math.floor(difference / 1000); $('#counter-days').textContent = Math.floor(seconds / 86400); $('#counter-hours').textContent = Math.floor(seconds % 86400 / 3600); $('#counter-minutes').textContent = Math.floor(seconds % 3600 / 60); $('#counter-seconds').textContent = seconds % 60; note.hidden = true; }; update(); counterTimer = setInterval(update, 1000); }
function renderResultAlbum() { const section = $('#album-section'); const container = $('#result-album'); section.hidden = !data.album.length; container.innerHTML = data.album.map((url, index) => `<button type="button" data-album-index="${index}" aria-label="Mở ảnh ${index + 1}"><img src="${url}" alt="Ảnh kỷ niệm ${index + 1}"></button>`).join(''); $$('#result-album button').forEach((button) => button.addEventListener('click', () => openLightbox(Number(button.dataset.albumIndex)))); }
function renderLetter() { const section = $('#letter-section'); section.hidden = !data.letter; $('#result-letter').textContent = data.letter; $('#envelope-button').classList.remove('is-open'); section.classList.remove('is-open'); $('#envelope-button').setAttribute('aria-expanded', 'false'); }
function renderQR() { const section = $('#qr-section'); section.hidden = !data.qrEnabled || !data.qrContent; const container = $('#qrcode'); container.innerHTML = ''; if (section.hidden) return; if (window.QRCode) new QRCode(container, { text: data.qrContent, width: 160, height: 160, colorDark: '#44343c', colorLight: '#ffffff' }); else { const fallback = document.createElement('p'); fallback.textContent = 'QR Code cần kết nối mạng để tạo. Nội dung: ' + data.qrContent; container.append(fallback); } }
function renderMusic() { const section = $('#result-music'); const audio = $('#result-audio'); section.hidden = data.musicMode !== 'music' || !data.musicData; if (section.hidden) { audio.pause(); audio.removeAttribute('src'); return; } audio.src = data.musicData; $('#result-music-name').textContent = data.musicName || 'Giai điệu của chúng mình'; $('#music-state').textContent = 'Tạm dừng'; $('#music-toggle').textContent = '▶'; }
function openLightbox(index) { currentLightboxIndex = index; $('#lightbox-image').src = data.album[index]; $('#lightbox').hidden = false; }
function closeLightbox() { $('#lightbox').hidden = true; }
function cycleLightbox(direction) { if (!data.album.length) return; currentLightboxIndex = (currentLightboxIndex + direction + data.album.length) % data.album.length; $('#lightbox-image').src = data.album[currentLightboxIndex]; }
function createParticle(kind = 'particle', x, y) { const characters = ['❤️', '💕', '💗', '💖', '💘', '💓', '💞', '✨']; const item = document.createElement('span'); item.className = kind; item.textContent = characters[Math.floor(Math.random() * characters.length)]; item.style.setProperty('--size', `${.7 + Math.random() * 1.1}rem`); item.style.setProperty('--duration', `${4 + Math.random() * 4}s`); item.style.setProperty('--opacity', `${.35 + Math.random() * .5}`); item.style.setProperty('--drift', `${-90 + Math.random() * 180}px`); item.style.setProperty('--rotate', `${-35 + Math.random() * 70}deg`); if (kind === 'touch-heart') { item.style.left = `${x}px`; item.style.top = `${y}px`; item.style.setProperty('--drift-x', `${-65 + Math.random() * 130}px`); item.style.setProperty('--drift-y', `${-35 - Math.random() * 80}px`); } else item.style.left = `${Math.random() * 100}%`; $('#particle-layer').append(item); item.addEventListener('animationend', () => item.remove()); }
function startParticles(intense = false) { if (prefersReducedMotion) return; const layer = $('#particle-layer'); $$('.particle', layer).forEach((item) => item.remove()); const amount = intense ? 25 : 8; for (let i = 0; i < amount; i += 1) setTimeout(() => createParticle(), i * 100); if (!intense) { clearInterval(particleTimer); particleTimer = setInterval(() => { if (!screens.love.hidden && $$('.particle', layer).length < 14) createParticle(); }, 950); } }
function startSparkles() { if (prefersReducedMotion) return; const layer = $('#sparkle-layer'); for (let i = 0; i < 14; i += 1) { const sparkle = document.createElement('span'); sparkle.className = 'sparkle'; sparkle.textContent = '✦'; sparkle.style.left = `${5 + Math.random() * 90}%`; sparkle.style.top = `${5 + Math.random() * 90}%`; sparkle.style.setProperty('--size', `${.45 + Math.random() * .45}rem`); sparkle.style.setProperty('--duration', `${2.5 + Math.random() * 3}s`); sparkle.style.animationDelay = `${Math.random() * 3}s`; layer.append(sparkle); } }
function burstAt(x, y) { if (prefersReducedMotion || screens.love.hidden) return; for (let i = 0; i < 5; i += 1) { const item = document.createElement('span'); item.className = 'touch-heart'; item.textContent = ['♥', '♡', '✦'][i % 3]; item.style.left = `${x}px`; item.style.top = `${y}px`; item.style.setProperty('--size', `${.7 + Math.random() * .6}rem`); item.style.setProperty('--drift-x', `${-55 + Math.random() * 110}px`); item.style.setProperty('--drift-y', `${-30 - Math.random() * 70}px`); $('#touch-hearts').append(item); item.addEventListener('animationend', () => item.remove()); } }
function openLovePage() { showScreen(screens.love); startParticles(true); setTimeout(() => startParticles(false), 1800); startSparkles(); if (data.musicMode === 'music' && data.musicData) { const audio = $('#result-audio'); audio.play().then(() => { $('#music-state').textContent = 'Đang phát'; $('#music-toggle').textContent = '❚❚'; }).catch(() => { /* Autoplay is optional; the player remains available. */ }); } }

inputs.senderPhoto.addEventListener('change', () => handleSingleImage('senderPhoto')); inputs.receiverPhoto.addEventListener('change', () => handleSingleImage('receiverPhoto')); inputs.albumPhotos.addEventListener('change', handleAlbum); inputs.musicFile.addEventListener('change', handleMusic); inputs.message.addEventListener('input', () => syncCounter(inputs.message, $('#character-count'))); inputs.letter.addEventListener('input', () => syncCounter(inputs.letter, $('#letter-count'))); $$('input[name="musicMode"]').forEach((input) => input.addEventListener('change', syncOptionalSections)); $('#qr-enabled').addEventListener('change', syncOptionalSections);
form.addEventListener('submit', (event) => { event.preventDefault(); showStatus(''); if (!validate()) return; readForm(); saveData(); renderResult(); });
$('#open-button').addEventListener('click', openLovePage); $('#edit-button').addEventListener('click', () => showScreen(screens.form)); $('#envelope-button').addEventListener('click', () => { const button = $('#envelope-button'); const open = !button.classList.contains('is-open'); button.classList.toggle('is-open', open); $('#letter-section').classList.toggle('is-open', open); button.setAttribute('aria-expanded', String(open)); }); $('#lightbox-close').addEventListener('click', closeLightbox); $('#lightbox-prev').addEventListener('click', () => cycleLightbox(-1)); $('#lightbox-next').addEventListener('click', () => cycleLightbox(1)); $('#lightbox').addEventListener('click', (event) => { if (event.target.id === 'lightbox') closeLightbox(); }); $('#music-toggle').addEventListener('click', () => { const audio = $('#result-audio'); if (audio.paused) audio.play().then(() => { $('#music-state').textContent = 'Đang phát'; $('#music-toggle').textContent = '❚❚'; }).catch(() => { $('#music-state').textContent = 'Không thể phát file nhạc'; }); else { audio.pause(); $('#music-state').textContent = 'Tạm dừng'; $('#music-toggle').textContent = '▶'; } }); document.addEventListener('click', (event) => { if (!screens.love.hidden) burstAt(event.clientX, event.clientY); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeLightbox(); if (!screens.love.hidden && event.key === 'ArrowRight') cycleLightbox(1); if (!screens.love.hidden && event.key === 'ArrowLeft') cycleLightbox(-1); });
$('#new-page-button').addEventListener('click', () => { localStorage.removeItem(STORAGE_KEY); form.reset(); data = { senderName: '', receiverName: '', message: '', letter: '', specialDate: '', senderPhoto: '', receiverPhoto: '', album: [], musicMode: 'none', musicName: '', musicData: '', qrEnabled: false, qrContent: '' }; imageUrls = { ...imageDefaults }; selectedAlbum = []; updateImagePreview('senderPhoto', imageDefaults.senderPhoto); updateImagePreview('receiverPhoto', imageDefaults.receiverPhoto); renderAlbumPreview(); syncOptionalSections(); syncCounter(inputs.message, $('#character-count')); syncCounter(inputs.letter, $('#letter-count')); $('#music-name').textContent = 'Chọn file MP3'; $('#music-preview').hidden = true; $('#saved-dialog').hidden = true; }); $('#saved-page-button').addEventListener('click', () => { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); populateForm(saved); $('#saved-dialog').hidden = true; renderResult(); });
(function init() { syncOptionalSections(); syncCounter(inputs.message, $('#character-count')); syncCounter(inputs.letter, $('#letter-count')); const previewValue = new URLSearchParams(window.location.hash.slice(1)).get('preview'); if (previewValue) { try { const previewData = JSON.parse(decodeURIComponent(previewValue)); data = { ...data, ...previewData }; imageUrls.senderPhoto = data.senderPhoto || imageDefaults.senderPhoto; imageUrls.receiverPhoto = data.receiverPhoto || imageDefaults.receiverPhoto; selectedAlbum = Array.isArray(data.album) ? data.album : []; renderResult(); } catch { showStatus('Không thể tải bản preview này.'); } return; } const savedRaw = localStorage.getItem(STORAGE_KEY); if (!savedRaw) return; try { const saved = JSON.parse(savedRaw); if (saved && saved.senderName && saved.receiverName) $('#saved-dialog').hidden = false; } catch { localStorage.removeItem(STORAGE_KEY); } })();
